server:
  port: 30011

spring:
  application:
    name: eurekaClient
  zipkin:
    baseUrl: http://127.0.0.1:9411/
    sleuth:
      sampler:
        probability: 1

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true