
datasource:
  write:
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.0.41.80:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=Asia/Shanghai
  read:
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://10.0.41.80:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=Asia/Shanghai
logging:
  level:
    root: info
    cn.nihility: debug
    org.mybatis: debug
